-- PMS schema (V1). Run once against pms_demo, before starting pms-app.
-- Generated from the JPA entities in pms-db (PostgreSQL dialect): 17 tables, camelCase -> snake_case columns.
-- Not idempotent: running it again fails with "relation already exists". To reset, drop the pms schema
-- (DROP SCHEMA pms CASCADE) first, and only if it holds no data you need.

CREATE SCHEMA IF NOT EXISTS pms;

create table pms.competency_master (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, status varchar(20) not null check ((status in ('ACTIVE','INACTIVE'))), category varchar(100) not null, name varchar(200) not null, created_by varchar(255), modified_by varchar(255), organisation_id varchar(255) not null, primary key (id));
create table pms.goal_template (effective_from date not null, is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, financial_year varchar(20) not null, status varchar(20) not null check ((status in ('DRAFT','ACTIVE','INACTIVE'))), template_name varchar(200) not null, created_by varchar(255), department_id varchar(255) not null, description TEXT, modified_by varchar(255), organisation_id varchar(255) not null, plant_id varchar(255), role_id varchar(255) not null, primary key (id));
create table pms.goal_template_competency (display_order integer, is_active boolean default true not null, weightage numeric(5,2) not null, created_date timestamp(6), modified_date timestamp(6), competency_id uuid not null, id uuid not null, template_id uuid not null, created_by varchar(255), modified_by varchar(255), primary key (id), constraint uk_goal_template_competency_template_competency unique (template_id, competency_id));
create table pms.goal_template_kpi (display_order integer, is_active boolean default true not null, weightage numeric(5,2) not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, kpi_id uuid not null, kra_id uuid not null, template_id uuid not null, target_type varchar(30) not null check ((target_type in ('COMMON','INDIVIDUAL'))), created_by varchar(255), modified_by varchar(255), primary key (id), constraint uk_goal_template_kpi_template_kpi unique (template_id, kpi_id));
create table pms.goal_template_kra (display_order integer, is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, kra_id uuid not null, template_id uuid not null, created_by varchar(255), modified_by varchar(255), primary key (id), constraint uk_goal_template_kra_template_kra unique (template_id, kra_id));
create table pms.kpi_master (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, kra_id uuid not null, status varchar(20) not null check ((status in ('ACTIVE','INACTIVE'))), target_type varchar(30) not null check ((target_type in ('COMMON','INDIVIDUAL'))), unit varchar(50) not null, name varchar(200) not null, evidence_required varchar(500), expected_outcome varchar(500), created_by varchar(255), modified_by varchar(255), organisation_id varchar(255) not null, primary key (id));
create table pms.kra_master (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, status varchar(20) not null check ((status in ('ACTIVE','INACTIVE'))), name varchar(200) not null, created_by varchar(255), modified_by varchar(255), organisation_id varchar(255) not null, primary key (id));
create table pms.pms_cycle (completed_step integer not null, current_step integer not null, is_active boolean default true not null, notify_employees boolean not null, notify_hod boolean not null, notify_hr boolean not null, notify_managers boolean not null, period_end date not null, period_start date not null, created_date timestamp(6), modified_date timestamp(6), published_on timestamp(6), id uuid not null, rating_scale_id uuid, status varchar(20) not null check ((status in ('DRAFT','ACTIVE','CLOSED','CANCELLED'))), type varchar(20) not null check ((type in ('ANNUAL','MID_YEAR','CUSTOM'))), cycle_code varchar(30) not null unique, name varchar(200) not null, created_by varchar(255), description TEXT, modified_by varchar(255), organisation_id varchar(255) not null, primary key (id));
create table pms.pms_cycle_applicability (all_departments boolean not null, all_plants boolean not null, exclude_notice_period boolean not null, exclude_probation boolean not null, is_active boolean default true not null, minimum_service_months integer, service_calculated_as_on date, created_date timestamp(6), modified_date timestamp(6), cycle_id uuid not null unique, id uuid not null, created_by varchar(255), modified_by varchar(255), primary key (id));
create table pms.pms_cycle_department (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), cycle_id uuid not null, id uuid not null, created_by varchar(255), department_id varchar(255) not null, modified_by varchar(255), primary key (id), constraint uk_pms_cycle_department_cycle_dept unique (cycle_id, department_id));
create table pms.pms_cycle_eligibility_run (excluded_min_service integer not null, excluded_notice_period integer not null, excluded_probation integer not null, is_active boolean default true not null, total_eligible integer not null, completed_on timestamp(6), created_date timestamp(6), modified_date timestamp(6), started_on timestamp(6) not null, cycle_id uuid not null, id uuid not null, status varchar(20) not null check ((status in ('STARTED','COMPLETED','FAILED'))), created_by varchar(255), error_message TEXT, modified_by varchar(255), primary key (id));
create table pms.pms_cycle_employment_type (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), cycle_id uuid not null, id uuid not null, employment_type varchar(30) not null check ((employment_type in ('PERMANENT','CONTRACT','TRAINEE'))), created_by varchar(255), modified_by varchar(255), primary key (id), constraint uk_pms_cycle_employment_type_cycle_type unique (cycle_id, employment_type));
create table pms.pms_cycle_notification (is_active boolean default true not null, sent_count integer not null, created_date timestamp(6), modified_date timestamp(6), sent_on timestamp(6), cycle_id uuid not null, id uuid not null, status varchar(20) not null check ((status in ('PENDING','SENT','FAILED','PARTIAL'))), audience varchar(40) not null check ((audience in ('HOD_REVIEWERS','REPORTING_MANAGERS','EMPLOYEES','HR'))), created_by varchar(255), error_message TEXT, modified_by varchar(255), primary key (id));
create table pms.pms_cycle_plant (is_active boolean default true not null, created_date timestamp(6), modified_date timestamp(6), cycle_id uuid not null, id uuid not null, created_by varchar(255), modified_by varchar(255), plant_id varchar(255) not null, primary key (id), constraint uk_pms_cycle_plant_cycle_plant unique (cycle_id, plant_id));
create table pms.pms_cycle_stage (end_date date, is_active boolean default true not null, notification_enabled boolean not null, start_date date, created_date timestamp(6), modified_date timestamp(6), cycle_id uuid not null, id uuid not null, stage varchar(60) not null check ((stage in ('GOAL_SETTING','EMPLOYEE_ACKNOWLEDGEMENT','HOD_APPROVAL','PROGRESS_TRACKING','MID_YEAR_REVIEW','SELF_APPRAISAL','MANAGER_APPRAISAL','HOD_REVIEW','CALIBRATION_FINAL_APPROVAL'))), created_by varchar(255), modified_by varchar(255), primary key (id), constraint uk_pms_cycle_stage_cycle_stage unique (cycle_id, stage));
create table pms.rating_scale (is_active boolean default true not null, is_default boolean not null, show_definitions_to_employees boolean not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, status varchar(20) not null check ((status in ('ACTIVE','INACTIVE'))), name varchar(150) not null, created_by varchar(255), description TEXT, modified_by varchar(255), organisation_id varchar(255) not null, primary key (id));
create table pms.rating_scale_level (display_order integer, is_active boolean default true not null, maximum_score numeric(5,2), minimum_score numeric(5,2), rating_value integer not null, created_date timestamp(6), modified_date timestamp(6), id uuid not null, rating_scale_id uuid not null, colour_code varchar(20), label varchar(100) not null, created_by varchar(255), definition TEXT, modified_by varchar(255), primary key (id), constraint uk_rating_scale_level_scale_value unique (rating_scale_id, rating_value));
create index idx_competency_master_org on pms.competency_master (organisation_id);
create index idx_competency_master_category on pms.competency_master (category);
create index idx_competency_master_status on pms.competency_master (status);
create index idx_competency_master_name on pms.competency_master (name);
create index idx_goal_template_org on pms.goal_template (organisation_id);
create index idx_goal_template_fy on pms.goal_template (financial_year);
create index idx_goal_template_department on pms.goal_template (department_id);
create index idx_goal_template_role on pms.goal_template (role_id);
create index idx_goal_template_plant on pms.goal_template (plant_id);
create index idx_goal_template_status on pms.goal_template (status);
create index idx_goal_template_effective_from on pms.goal_template (effective_from);
create index idx_goal_template_competency_template on pms.goal_template_competency (template_id);
create index idx_goal_template_competency_competency on pms.goal_template_competency (competency_id);
create index idx_goal_template_kpi_template on pms.goal_template_kpi (template_id);
create index idx_goal_template_kpi_kra on pms.goal_template_kpi (kra_id);
create index idx_goal_template_kpi_kpi on pms.goal_template_kpi (kpi_id);
create index idx_goal_template_kra_template on pms.goal_template_kra (template_id);
create index idx_goal_template_kra_kra on pms.goal_template_kra (kra_id);
create index idx_kpi_master_org on pms.kpi_master (organisation_id);
create index idx_kpi_master_kra on pms.kpi_master (kra_id);
create index idx_kpi_master_status on pms.kpi_master (status);
create index idx_kpi_master_name on pms.kpi_master (name);
create index idx_kra_master_org on pms.kra_master (organisation_id);
create index idx_kra_master_status on pms.kra_master (status);
create index idx_kra_master_name on pms.kra_master (name);
create index idx_pms_cycle_org on pms.pms_cycle (organisation_id);
create index idx_pms_cycle_status on pms.pms_cycle (status);
create index idx_pms_cycle_type on pms.pms_cycle (type);
create index idx_pms_cycle_period_start on pms.pms_cycle (period_start);
create index idx_pms_cycle_created_date on pms.pms_cycle (created_date);
create index idx_pms_cycle_rating_scale on pms.pms_cycle (rating_scale_id);
create index idx_pms_cycle_department_cycle on pms.pms_cycle_department (cycle_id);
create index idx_pms_cycle_department_dept on pms.pms_cycle_department (department_id);
create index idx_pms_cycle_eligibility_run_cycle on pms.pms_cycle_eligibility_run (cycle_id);
create index idx_pms_cycle_eligibility_run_status on pms.pms_cycle_eligibility_run (status);
create index idx_pms_cycle_eligibility_run_started on pms.pms_cycle_eligibility_run (started_on);
create index idx_pms_cycle_employment_type_cycle on pms.pms_cycle_employment_type (cycle_id);
create index idx_pms_cycle_notification_cycle on pms.pms_cycle_notification (cycle_id);
create index idx_pms_cycle_notification_audience on pms.pms_cycle_notification (audience);
create index idx_pms_cycle_notification_status on pms.pms_cycle_notification (status);
create index idx_pms_cycle_plant_cycle on pms.pms_cycle_plant (cycle_id);
create index idx_pms_cycle_plant_plant on pms.pms_cycle_plant (plant_id);
create index idx_pms_cycle_stage_cycle on pms.pms_cycle_stage (cycle_id);
create index idx_pms_cycle_stage_stage on pms.pms_cycle_stage (stage);
create index idx_rating_scale_org on pms.rating_scale (organisation_id);
create index idx_rating_scale_status on pms.rating_scale (status);
create index idx_rating_scale_default on pms.rating_scale (is_default);
create index idx_rating_scale_level_scale on pms.rating_scale_level (rating_scale_id);
alter table if exists pms.goal_template_competency add constraint FK45mhdk98don6aqc13y880qg7c foreign key (competency_id) references pms.competency_master;
alter table if exists pms.goal_template_competency add constraint FKd82n2y97en6woh9gdkqt4evhf foreign key (template_id) references pms.goal_template;
alter table if exists pms.goal_template_kpi add constraint FKj0ricjpe3g0mfwsgoqox4mr0q foreign key (kpi_id) references pms.kpi_master;
alter table if exists pms.goal_template_kpi add constraint FK6idjo66fky1b49182bantihja foreign key (kra_id) references pms.kra_master;
alter table if exists pms.goal_template_kpi add constraint FKg667wvkyemi94b3fs2wl1d3wf foreign key (template_id) references pms.goal_template;
alter table if exists pms.goal_template_kra add constraint FKri7u0pgjbnop6a62x19uos5a6 foreign key (kra_id) references pms.kra_master;
alter table if exists pms.goal_template_kra add constraint FKi0mv08nq5tqhgex8d1xcg9rpr foreign key (template_id) references pms.goal_template;
alter table if exists pms.kpi_master add constraint FK3yjagbi7fgwdjon6kdvactu8w foreign key (kra_id) references pms.kra_master;
alter table if exists pms.pms_cycle_applicability add constraint FKb32icle7pu9bgm8a731x5bu5 foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_department add constraint FKt3lir8bvaat9ybkp2rs6vbbcg foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_eligibility_run add constraint FKjdsor7es2pfn0dqwg0jc730ov foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_employment_type add constraint FKp1hl9p2scbcehkfwoi0s4aexe foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_notification add constraint FKg5vxcragan1rrh0894biy2cfm foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_plant add constraint FKpsrwpjlrl75w9h1koat4g8kju foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.pms_cycle_stage add constraint FK93cbqhi9jdl0qrd0xbm5noupq foreign key (cycle_id) references pms.pms_cycle;
alter table if exists pms.rating_scale_level add constraint FKexxmn2ld1qxhlesgfrdbljptx foreign key (rating_scale_id) references pms.rating_scale;
